baseURL = "/"
languageCode = "en-us"
title = "Open Coaching & Consultancy"
theme = "ananke"

[menu]

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

  [[menu.main]]
  name = "Services"
  url = "/services/"
  weight = 2

  [[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 3

[params]
  customCSS = ["css/custom.css"]
